# Generated by Django 4.1.2 on 2023-09-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_imagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
